version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 5435
    expose:
      - 5435
    env_file:
      .env-prod

  app:
    build:
      context: .
    env_file:
      .env-prod
    container_name: weather_api
    command: ["/weather_api/docker/app.sh"]
    ports:
      - 7373:8000
    depends_on:
      - db
